### ISSUE TITLE
 Issue with Redirect in Adding New Subsection

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/app-vlead-web#26]
When attempting to add a new subsection titled "Report a Workshop" under the existing section "Request a workshop" in the [outreach.json file](https://github.com/virtual-labs/app-vlead-web/blob/main/src/outreach.json), the redirection behaves unexpectedly. Instead of directing to the intended link, which is [here](https://raw.githubusercontent.com/virtual-labs/app-outreach-tracker-web/dev/docs/nc-help-doc.md), it redirects to the link associated with "Request a workshop".

**Steps to Reproduce:**
- Navigate to the [outreach.json file](https://github.com/virtual-labs/app-vlead-web/blob/main/src/outreach.json).
- Locate the section titled "Request a workshop".
- Attempt to add a new subsection titled "Report a Workshop" below "Request a workshop".
- Observe the redirection behavior.

**Expected Behavior:**
When clicking on the "Report a Workshop" subsection, users should be directed to the [specified link](https://raw.githubusercontent.com/virtual-labs/app-outreach-tracker-web/dev/docs/nc-help-doc.md).

**Actual Behavior:**
Currently, clicking on the "Report a Workshop" subsection redirects users to the link associated with "Request a workshop" instead of the specified link.

Please find the attached screenshot
![Screenshot from 2024-05-15 12-03-36](https://github.com/virtual-labs/app-vlead-web/assets/15810190/6fe37a98-4cf4-4ee8-9636-9a6db36109ee)

**Comment by 112Nisha** [comment]
The code in the dev branch for the website now uses outreach.json as a template for Workshops and Nodal Centers

**Comment by 112Nisha** [comment]
The code in the dev branch for the website now uses outreach.json as a template for Workshops and Nodal Centers
