### ISSUE TITLE
Analytics Data Not Updated

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/app-vlead-web#27]
**Description**
The analytics data on the [VLEAD Web Application](https://virtual-labs.github.io/app-vlead-web/) is not getting updated. This issue needs to be addressed to ensure accurate and up-to-date analytics information is displayed on the website.

**Expected Behavior**
The analytics data should be regularly updated and accurately reflect the information from the specified Google Sheets document.

**Current Behavior**
Currently, the analytics data on the website is outdated and does not reflect the latest information.

**Steps to Reproduce**
- Open the [VLEAD Web Application](https://virtual-labs.github.io/app-vlead-web/).
- Analytics data is on the top right corner of the page.
- Compare the displayed data with the data in the specified [Google Sheet](https://docs.google.com/spreadsheets/d/1x12nhpp0QvnsA6x-O1sV4IA9SAbfVsq_wiexWkutOmU/edit#gid=1573630614).

**Source of Data**
The updated data should be sourced from the following Google Sheets document:
- [Google Sheets](https://docs.google.com/spreadsheets/d/1x12nhpp0QvnsA6x-O1sV4IA9SAbfVsq_wiexWkutOmU/edit#gid=1573630614)
- Use the data from the "Total-Users" tab.

**Attachments**
![Screenshot from 2024-06-14 13-16-27](https://github.com/virtual-labs/app-vlead-web/assets/15810190/45762afe-8a36-4031-9078-bdd8dcff0ea4)

**Comment by 112Nisha** [comment]
The navbar now displays the correct number of users and views
